In [3]:
import os

print("Current folder:")
print(os.getcwd())

print("\nFiles in this folder:")
print(os.listdir())

Current folder:
C:\Users\jeeva\Desktop

Files in this folder:
['.ipynb_checkpoints', '5-sem', '798654', 'amsdproj-codex-create-college-food-delivery-webpage-299npw', 'Antigravity.lnk', 'B.Tech - V Semester End Examinations Regular (AUS24) - NOV 2026.pdf', 'B.Tech_CSE_ProgramStructure_Syllabus.pdf', 'Business Logic Workflow.docx', 'CD Lab', 'Cisco Networking Academy.lnk', 'codechef.lnk', 'CS_GATE2027_Syllabus.pdf', 'Dashboard - Naukri Code 360 (Person 1).lnk', 'DeepSeek.lnk', 'desktop.ini', 'Dev-C++.lnk', 'Discord.lnk', 'Edusat Registrations (B).lnk', 'GA_GATE2027_Syllabus.pdf', 'govt-subsidy-disbursement-tracking-system', 'hackathon', 'hackathon.worktrees', 'HackerRank.lnk', 'Imsd Code', 'info', 'java project sem-4', 'jeevanmanojsai14 - Codeforces (jeevan).lnk', 'jeevanmanojsai_resume.pdf', 'jupyter lab.bat', 'Mail - 24B11CS036 - Outlook (Person 1).lnk', "manoj's project", 'MinGW Installer.lnk', 'ml Lab', 'MongoDB Compass.lnk', 'new project -s', 'OOAD EV', 'palla praneeth navodaya.pdf', 'Postman.lnk', 'Problems - LeetCode (jeevan).lnk', 'resume_intership.pdf', 'sem-5 projects', 'Summer Internship 26-27 Template- University.docx', 'summer intership-11', 'Telegram.lnk', 'Time Table for B.Tech V Semester Internal Examinations - II OCT 2026.pdf', 'Untitled.ipynb', 'vscode', 'WhatsApp Image 2026-09-10 at 19.48.14.jpeg', 'WhatsApp Image 2026-09-10 at 19.48.15.jpeg', '~$ IMP Questions.docx', '~$it-3,4,5 (mid-2).docx', '~$sd record manoj.docx']

In [5]:
import os

os.chdir(r"C:\Users\jeeva\Desktop\sem-5 projects\ML Project\Smart Agriculture Prediction System Using Machine Learning")

print("Current folder:")
print(os.getcwd())

Current folder:
C:\Users\jeeva\Desktop\sem-5 projects\ML Project\Smart Agriculture Prediction System Using Machine Learning

In [6]:
print(os.listdir())

['.ipynb_checkpoints', 'app.py', 'Crop Recommendation Using Machine Learning.ipynb', 'Crop_recommendation.csv', 'minmaxscaler.pkl', 'model.pkl', 'README.md', 'standscaler.pkl', 'static', 'templates']

In [7]:
import pandas as pd

df = pd.read_csv("Crop_recommendation.csv")

print("RAW DATA")
display(df.head(10))

print("Shape:", df.shape)

RAW DATA

    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice
5  69  37  42    23.058049  83.370118  7.073454  251.055000  rice
6  69  55  38    22.708838  82.639414  5.700806  271.324860  rice
7  94  53  40    20.277744  82.894086  5.718627  241.974195  rice
8  89  54  38    24.515881  83.535216  6.685346  230.446236  rice
9  68  58  38    23.223974  83.033227  6.336254  221.209196  rice

Shape: (2200, 8)

In [10]:
import warnings
warnings.filterwarnings("ignore")

import pickle
import numpy as np
import pandas as pd

# Load the same scalers used by app.py
with open("minmaxscaler.pkl", "rb") as f:
    mx = pickle.load(f)

with open("standscaler.pkl", "rb") as f:
    sc = pickle.load(f)

features = [
    "N", "P", "K",
    "temperature", "humidity",
    "ph", "rainfall"
]

# Convert to NumPy array, just like app.py
X = df[features].values

# EXACT SAME ORDER AS app.py
X_minmax = mx.transform(X)
X_preprocessed = sc.transform(X_minmax)

preprocessed_df = pd.DataFrame(
    X_preprocessed,
    columns=features
)

print("PREPROCESSED DATA")
display(preprocessed_df.head(10))

PREPROCESSED DATA

      N     P    K   temperature      humidity            ph      rainfall
0   0.0   0.0  0.0 -2.900000e-07  2.300000e-07  2.920000e-07  2.000000e-07
1  -5.0  16.0 -2.0  8.907177e-01 -1.683100e+00  5.351114e-01  2.372000e+01
2 -30.0  13.0  1.0  2.124715e+00  3.180189e-01  1.337222e+00  6.102871e+01
3 -16.0  -7.0 -3.0  5.611352e+00 -1.844381e+00  4.774159e-01  3.992850e+01
4 -12.0   0.0 -1.0 -7.495692e-01 -3.978711e-01  1.125488e+00  5.978180e+01
5 -21.0  -5.0 -1.0  2.178305e+00  1.367374e+00  5.704685e-01  4.811946e+01
6 -21.0  13.0 -5.0  1.829094e+00  6.366699e-01 -8.021793e-01  6.838932e+01
7   4.0  11.0 -3.0 -6.020004e-01  8.913422e-01 -7.843578e-01  3.903866e+01
8  -1.0  12.0 -5.0  3.636137e+00  1.532472e+00  1.823614e-01  2.751070e+01
9 -22.0  16.0 -5.0  2.344230e+00  1.030483e+00 -1.667315e-01  1.827366e+01